### ISSUE TITLE
Fails To Build From Source, GCC-7 (rawhide)

### ISSUE THREAD

**Issue by kuboosoft** [UnitedRPMs/chromium-freeworld#2]
We have the same problem reported in [Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853347)....

**Comment by paulcarroty** [comment]
The last builds from Spot also failed: https://koji.fedoraproject.org/koji/packageinfo?packageID=22672

**Comment by kuboosoft** [comment]
In Fedora 24 and 25 compiled fine. Chromium in Rawhide affected thanks to gcc7...
