### ISSUE TITLE
Not requiring u2f-hidraw-policy

### ISSUE THREAD

**Issue by phipolis** [UnitedRPMs/chromium-freeworld#3]
The Fedora version of chromium installs `u2f-hidraw-policy`, while chromium-freeworld does not. I'm not sure if that's simply a matter of the require being missing from the RPM, or if the feature also needs to be     enabled when building chromium. Either way, it'd be great if chromium-freeworld could support U2F tokens as well as chrome and chromium do.

**Comment by kuboosoft** [comment]
Hi! the fedora chromiun installs u2f-hidraw-policy as a dependency; Theoretically this should be installed automatically, without the need to add it to a "requires"

http://pkgs.fedoraproject.org/cgit/rpms/chromium.git/tree/chromium.spec#n369
http://pkgs.fedoraproject.org/cgit/rpms/chromium.git/tree/chromium.spec#n1907

But we can enable u2f-hidraw-policy in the next update, thanks for your report :) Hey! now we have our [gitter community](https://gitter.im/unitedrpms-people/Lobby) :)

**Comment by phipolis** [comment]
Thanks! I noticed because when removing chromium after installing chromium-freeworld, dnf uninstalled u2f-hidraw-policy as "Removing unused dependencies"

**Comment by kuboosoft** [comment]
@phipolis solved in new release, only wait 24 hours.
