### ISSUE TITLE
Fedora 27 to 28 upgrade gives "Aw, Snap!" for all pages

### ISSUE THREAD

**Issue by AJCxZ0** [UnitedRPMs/chromium-freeworld#7]
Upgraded Fedora 27 to 28. Opening chromium-freeworld gave "Aw, Snap!" for all pages opened.
Moved the profile (.config/chromium) and launched with the same result. Literally all pages - even the blank page and chrome:// pages give the same result.

> chromium-freeworld-66.0.3359.170-7.fc28.x86_64
> chromium-freeworld-libs-66.0.3359.170-7.fc28.x86_64
> chromium-freeworld-libs-media-66.0.3359.170-7.fc28.x86_64
> chromium-widevine-1.4.9.1076-1.fc28.x86_64
> chromium-pepper-flash-29.0.0.171-1.fc28.x86_64

Google Chrome works fine. I've not tried chromium.

**Comment by kuboosoft** [comment]
Yes; our chromium-freeworl 66 is broken... and maybe is necessary enable some features; but it take time. Build chromium takes 8-12 hours... The solution; put again our chromium 65 (transitional) and downgrade... Chromium is as hell...
