### ISSUE TITLE
chromium-freeworld for fc29 is crazy slow

### ISSUE THREAD

**Issue by edgan** [UnitedRPMs/chromium-freeworld#8]
I have been suffering with chromium-freeworld on Fedora 29 since upgrading to Fedora 29. I don't know what it is about that build that makes it so slow. Extensions are slow to draw, connection lag, and cpu usage is way up. I run a profiles for work and personal. I use Slack and WhatsApp through chromium. All that makes it crawl. Moving Slack and WhatsApp to Chrome helped, but it was still bad. I downgraded to the fc28 build, and it seems to be better. Also chrome of the same version seems fine.

chromium-freeworld-69.0.3497.100-8.fc29.x86_64

**Comment by kuboosoft** [comment]
@edgan yes... recently changes makes very slow chromium, also in F29-Rawhide needs a rebuild thanks to vaapi... But don't worry a new update coming soon and it looks more fast... Brave browser, as a fast alternative is beautiful; the ironic is it is based in Chromium 69...

**Comment by edgan** [comment]
Does brave support extensions yet? When I last looked at it, no extensions.

**Comment by edgan** [comment]
Trying brave, and it does extensions, which is nice. But it freaks out worse than chromium-freeworld as soon as I create a third profile. Chrome/Chromium/Brave 69+ seems to hate multiple profiles.

**Comment by kuboosoft** [comment]
In the next hours our chromium-freeworld 70 is available; Tested a week it works, but lost the velocity comparated to 68 version... The bad in "Brave" is the support to widevine and chromecast...

**Comment by edgan** [comment]
I just tested the current chromium-freeworld on Fedora 29, and it isn't any better. It works till I open a second profile, and then it runs like a dog. I also upgraded to 69, and it is working normally. Brave works like chromium-freeworld.

brave-browser-0.55.22-1.x86_64
chromium-69.0.3497.100-1.fc29.x86_64
chromium-freeworld-70.0.3538.67-7.fc29.x86_64

**Comment by kuboosoft** [comment]
@edgan I recommend to delete chromium 69; because you will have two desktop files... mix a old profile with the new chromium may causes problems...

**Comment by kuboosoft** [comment]
@edgan I recommend to delete chromium 69; because you will have two desktop files... mix a old profile with the new chromium may cause problems... "dnf -y remove chromium-libs"

Other; I recommend to disable GPU acceleration if your chromium is slow... It works for me in my Intel graphic card...

You can see results

`chrome://gpu/`

**Comment by karolherbst** [comment]
I think there is some deeper issue with the chromium build.

I was doing some speedtests:

chromium-freeworld: https://beta.speedtest.net/result/8086429256
chromium (fc29): https://beta.speedtest.net/result/8086468250
firefox: https://beta.speedtest.net/result/8086427431

but when I switch the tab while doing the speedtest, the result is getting much better... maybe there is something enabled which shouldn't and it slows everything down?

Anyway, it's clearly a bug within the freeworld package.

**Comment by karolherbst** [comment]
actually, browsing through the changes.. enabling "optimize_for_size = true" is probably a bad idea as this can cause significant amount of speed

**Comment by karolherbst** [comment]
@edgan so, running the official fedora chromium package and this is way smoother than the unitedrpm one.... so I guess something is terribly wrong here.

For h.264 stuff I use firefox for now until this issue gets resolved.

**Comment by karolherbst** [comment]
also something which was odd is, that with the freeworld build some benchmarking stuff was always showing up with htop for the chromium process. Some flag on the process

**Comment by kuboosoft** [comment]
@karolherbst drastically changes coming soon; our chromium-freeworld now is super fast. The update coming soon in the next hours...
