### ISSUE TITLE
How to build ?

### ISSUE THREAD

**Issue by liberodark** [UnitedRPMs/chromium-freeworld#9]
Hi

How to build chromium only on fedora or is ok on other Distro ?
And on ARM64 is work ?

Best Regards

**Comment by kuboosoft** [comment]
@liberodark with your infraestructure you can do it (A machine Core i5/i7 8...16..RAM; 50GB in hd... and [mock](https://www.systutorials.com/docs/linux/man/1-mock/) (if exist the config); But our chromium isn't tested in ARM64... Maybe you need to patch & test some things... and here isn't our ground .
